### ISSUE TITLE
gen-php deletes target folder

### ISSUE THREAD

**Issue by mismosmi** [swaggest/json-cli#19]
Hi,
disclaimer: I'm new to json-schema and this is my first try to use it to produce some type models for my web API.

when I try to run gen-php on this very simple example file:
```json
{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
    "$id": "http://trek.michelsmola.de/schema/v3",
    "Something": {
        "title": "Something",
        "type": "object",
        "properties": {
            "name": {
                "type": "string"
            }
        }
    }
}
```
with this command:
```bash
json-cli gen-php simple.json --ns MyNamespace --ns-path ./json-schema-php
```
all it does is remove the targeted folder.

Might be an issue with my understanding of json-schema (do I need a type definition in the root-schema?) but deleting the folder still seems like a bug to me.

**Comment by vearutop** [comment]
Hi, by default root schema is used for code generation. In your example root schema is empty as it does not contain any constraints.

If you would like to generate a class for `Something`, you can do it with 
```
json-cli gen-php simple.json --ns MyNamespace --ns-path ./json-schema-php --ptr-in-schema '#/Something'
```
```php
<?php
/**
 * @file ATTENTION!!! The code below was carefully crafted by a mean machine.
 * Please consider to NOT put any emotional human-generated modifications as the splendid AI will throw them away with no mercy.
 */

namespace MyNamespace;

use Swaggest\JsonSchema\Constraint\Properties;
use Swaggest\JsonSchema\Schema;
use Swaggest\JsonSchema\Structure\ClassStructure;


/**
 * Something
 * Built from simple.json#/Something
 */
class SimpleJsonSomething extends ClassStructure
{
    /** @var string */
    public $name;

    /**
     * @param Properties|static $properties
     * @param Schema $ownerSchema
     */
    public static function setUpProperties($properties, Schema $ownerSchema)
    {
        $properties->name = Schema::string();
        $ownerSchema->type = Schema::OBJECT;
        $ownerSchema->title = "Something";
        $ownerSchema->setFromRef('simple.json#/Something');
    }
}
```

In order to clean up unused older files, all files that were not created during generation are removed from target directory. This also affects target directory itself.

Now that you raised a concern, I think such behavior could be improved indeed. I think it is worth changing cleanup to only delete unused `php` files and empty directories that were not empty before generation.
